version: "3.8"
services:
  mongodb:
    container_name: theoremforge-db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: theoremforge
    ports:
      - 27018:27017
    volumes:
      - ./persist/mongo-data:/data/db

  qdrant:
    image: qdrant/qdrant:latest
    container_name: theoremforge-qdrant
    restart: always
    ports:
      - "6333:6333"   # HTTP / REST API
      - "6334:6334"   # gRPC
    volumes:
      - ./qdrant_data:/qdrant/storage:z